### ISSUE TITLE
The browser list is out of date

### ISSUE THREAD

**Issue by kentalow** [oat-sa/extension-tao-clientdiag#309]
The browser list is out of date. How can I update this file?
https://oat-sa.github.io/browserslist-app-tao/api.json

**Comment by oatymart** [comment]
Hi @kentalow, TAO developers will take care of updating this library/app in the near future. I hope by next week, as we are quite busy at the moment. Thanks for the reminder!

**Comment by oatymart** [comment]
An update has been made to https://oat-sa.github.io/browserslist-app-tao/. I will close this issue now.
